# Generated by Django 2.1.7 on 2019-12-07 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creater'),
        ),
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Participant'),
        ),
    ]
