# Generated by Django 2.1.7 on 2019-12-07 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatRoom', '0002_auto_20191207_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Message sent'),
            preserve_default=False,
        ),
    ]
